name: build-and-publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v2
    - 
      name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - 
      name: Restore NuGet packages
      run: dotnet restore src/DemoGighubAction.WebApi/
    - 
      name: Build and test
      run: |
        dotnet build src/DemoGighubAction.WebApi/
        dotnet test src/DemoGighubAction.WebApi/
    - 
      name: Publish
      run: dotnet publish src/DemoGighubAction.WebApi/ -c Release -o publish
    - 
      name: Push to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: demo
        path: publish
    - 
      name: Publish image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        registry: docker.io
        repository: nuttaporn1449/demo
        tags: latest