name: build-and-publish

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - 
      name: checkout
      uses: actions/checkout@v1
    - 
      name: Login Docker Hub
      uses: docker/login-action@1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - 
      name: Setup docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:         
        push: true
        context: ./src/DemoGighubAction.WebApi
        file: ./src/DemoGighubAction.WebApi/Dockerfile
        tags: nuttaporn1449/demo:latest 
        labels: ${{ steps.meta.outputs.labels }}
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    