name: build-and-publish

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - 
      name: checkout
      uses: actions/checkout@v2
    - 
      name: Login Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    -
      name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: nuttaporn1449/demo
    -
      name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./src/DemoGighubAction.WebApi/
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}