name: build-and-publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up QENU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set up Docker Buildx
        run: docker/setup-buildx-action@v2
      
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./../src/DemoGighubAction.WebApi/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}